version: '3'
services:
  dart-db-local:
    container_name: dart-db-local
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: dart-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  dart-server-local:
    container_name: dart-server-local
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - dart-db-local
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dart-db-local:5432/dart-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - .:/dart
    ports:
      - '8080:8080'