ALTER TABLE university MODIFY university_id BIGINT AUTO_INCREMENT;
ALTER TABLE user MODIFY user_id BIGINT AUTO_INCREMENT;
ALTER TABLE friend MODIFY friend_id BIGINT AUTO_INCREMENT;
ALTER TABLE vote MODIFY vote_id BIGINT AUTO_INCREMENT;
ALTER TABLE question MODIFY question_id BIGINT AUTO_INCREMENT;
ALTER TABLE team MODIFY team_id BIGINT AUTO_INCREMENT;
ALTER TABLE region MODIFY region_id BIGINT AUTO_INCREMENT;
ALTER TABLE candidate MODIFY candidate_id BIGINT AUTO_INCREMENT;
ALTER TABLE profile_question MODIFY profile_question_id BIGINT AUTO_INCREMENT;
ALTER TABLE team_user MODIFY team_user_id BIGINT AUTO_INCREMENT;
ALTER TABLE team_region MODIFY team_region_id BIGINT AUTO_INCREMENT;

DROP TABLE IF EXISTS hibernate_sequence;








